
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: football-academy-app
    container_name: football_app
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    container_name: football_db
    restart: always
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: raseel2004
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
